language: python
python:
  - "3.5"
install: "pip install -r varia/requirements.txt"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - python -m unittest discover -s tests
  - coverage run tests/test_main.py
