language: python
python:
  - "3.6"
sudo: required
addons:
  apt:
    sources:
      - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
    packages:
      - xvfb
install:
  - "pip install -r requirements.txt"
  - pip install coverage
  - pip install codecov
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
#  - coverage run --source=. -m unittest discover -s test
#  - coverage report -m
  - python -m unittest discover -s test
  # -Please note: If this fails there may be a problem with the versions of the applications in requirements.txt
  #  This was a problem for Qt 5.10, for more info see this page: https://bugreports.qt.io/browse/QTBUG-64928
#after_success:
#  - codecov
notifications:
  email: false
