theme: jekyll-theme-dinky
title: Mindful Breathing title
description: A mindfulness application for people using the computer for extended periods of time, helping the user to stay in contact with the breath, the body, remembering to take breaks and to practice self-kindness
show_downloads: false
